### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by reubadoob** [yanone/raspberrypycryptobot#1]
`$ sudo python3 pycryptobot.py --market BTC-USD --granularity 3600 --sim fast --verbose 0
Traceback (most recent call last):
  File "pycryptobot.py", line 10, in <module>
    from models.PyCryptoBot import PyCryptoBot, truncate as _truncate
  File "/home/pycryptobot/models/PyCryptoBot.py", line 12, in <module>
    from models.Trading import TechnicalAnalysis
  File "/home/pycryptobot/models/Trading.py", line 11, in <module>
    from statsmodels.tsa.statespace.sarimax import SARIMAX, SARIMAXResultsWrapper
ModuleNotFoundError: No module named 'statsmodels'`

getting some missing modules when trying to run the test command. Any suggestions?

**Comment by reubadoob** [comment]
It appears the following 2 commands:

`sudo apt-get install python3-pandas python3-matplotlib`

and 

`pip3 install urllib3 requests statsmodels binance python-binance mock pytest pytest-mock`

are not installing the correct modules from `requirements.txt`

I fixed the issue by returning to the pycryptobot repository and running :

`sudo python3 -m pip install -r requirements.txt` 

All python issues are resolved and pycryptobot appears to be working.
