### ISSUE TITLE
Issue with later versions of PyCryptoBot

### ISSUE THREAD

**Issue by feliutg** [yanone/raspberrypycryptobot#3]
Hi yanone,

I have been using this bot for several months already and like a week ago it stopped working in my RPi. After several tries, installing/uninstalling websocket, websocket and websocket-client, I did some upgrades to apt-get packages, etc, etc I haven't being able to fix this issue with websockets. Something that was interesthing is that if I uninstall all the libraries related to websocket, the exact same message happens. Can you try on your version of the code with the latest pull of PyCryptoBot and comeback to see if you get the same issue? I am sure the only thing that changes is the source code, since I have it to automatically get the latest from git.

Thanks!

---------- Error Below -----------
Traceback (most recent call last):
  File "pycryptobot.py", line 17, in <module>
    from models.AppState import AppState
  File "/home/pi/PyCryptoBot/BTC-USD/models/AppState.py", line 5, in <module>
    from models.PyCryptoBot import PyCryptoBot
  File "/home/pi/PyCryptoBot/BTC-USD/models/PyCryptoBot.py", line 10, in <module                 >
    from models.exchange.binance import AuthAPI as BAuthAPI, PublicAPI as BPubli                 cAPI
  File "/home/pi/PyCryptoBot/BTC-USD/models/exchange/binance/__init__.py", line                  1, in <module>
    from .api import *
  File "/home/pi/PyCryptoBot/BTC-USD/models/exchange/binance/api.py", line 21, i                 n <module>
    from websocket import create_connection, WebSocketConnectionClosedException
ImportError: cannot import name 'create_connection' from 'websocket' (/home/pi/.                 local/lib/python3.7/site-packages/websocket/__init__.py)

**Comment by yanone** [comment]
Hey.
Sadly, I moved on from pycryptobot, not using this anymore, and the RPi has been repurposed.
I should and will reflect this in the README.
Really sorry that I won't be able to help.
